# -*- coding: utf-8 -*-
"""lab 6cv

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14croMvDyXvDwl-Hl0240Y2vRRJWRDEPq
"""

import cv2
from google.colab.patches import cv2_imshow

# Read the video
cap = cv2.VideoCapture('/content/demonslayer.mp4')

# Check if video opened successfully
if not cap.isOpened():
    print("Error: Could not open video.")
else:
    while True:
        ret, frame = cap.read()

        if not ret:
            break

        # Display video frame
        cv2_imshow(frame)

        # Slow motion (100 ms delay)
        if cv2.waitKey(100) & 0xFF == ord('q'):
            break

cap.release()
cv2.destroyAllWindows()