# -*- coding: utf-8 -*-
"""lab 20cv

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gIAmg5nlB0KMrandjmqipkKPlSu1F2YH
"""

import cv2
import numpy as np
from google.colab.patches import cv2_imshow

# Read the image
img = cv2.imread("/content/Picture1.png")

# Check if image is loaded
if img is None:
    print("Error: Could not load image.")
else:
    # Define sharpening kernel
    kernel = np.array([[0, 1, 0],
                       [1, -4, 1],
                       [0, 1, 0]])

    # Apply the filter
    sharpened = cv2.filter2D(img, -1, kernel)

    # Display original image
    print("Original Image:")
    cv2_imshow(img)

    # Display sharpened image
    print("Sharpened Image:")
    cv2_imshow(sharpened)

    # Save the output image
    cv2.imwrite("/content/Sharpened_Image.jpg", sharpened)

    print("Sharpened image saved successfully!")