# -*- coding: utf-8 -*-
"""lab 3 cv

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14croMvDyXvDwl-Hl0240Y2vRRJWRDEPq
"""

import cv2
from google.colab.patches import cv2_imshow

# Read the image
img = cv2.imread('/content/Picture1.png')

# Check if image is loaded
if img is None:
    print("Error: Could not load image.")
else:
    # Convert to grayscale
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

    # Detect edges using Canny
    edges = cv2.Canny(gray, 100, 200)

    # Save the edge image
    cv2.imwrite('/content/Canny_Edges_3rd.png', edges)

    # Display the edge image
    cv2_imshow(edges)

    print("Canny edge image saved as Canny_Edges_3rd.png")