# -*- coding: utf-8 -*-
"""lab 10cv

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gIAmg5nlB0KMrandjmqipkKPlSu1F2YH
"""

import cv2
from google.colab.patches import cv2_imshow

# Read the image
image = cv2.imread("/content/Picture1.png")

# Check if image is loaded
if image is None:
    print("Error: Could not load image.")
else:
    # Get width and height
    width = image.shape[1]
    height = image.shape[0]

    # Print image dimensions
    print("Width :", width)
    print("Height:", height)

    # Display the image
    cv2_imshow(image)

    # Save the image (optional)
    cv2.imwrite("/content/output_image.png", image)

    print("Image displayed and saved successfully!")