# -*- coding: utf-8 -*-
"""lab 5cv

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14croMvDyXvDwl-Hl0240Y2vRRJWRDEPq
"""

import cv2
from google.colab.patches import cv2_imshow

# Read the image
img = cv2.imread('/content/Picture1.png')

# Check if image loaded successfully
if img is None:
    print("Error: Could not load image.")
else:
    # Convert to grayscale
    gray_image = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

    # Create a 5x5 rectangular kernel
    kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (5, 5))

    # Perform erosion
    eroded_image = cv2.erode(gray_image, kernel, iterations=1)

    # Save the eroded image
    cv2.imwrite('/content/eroded_image.png', eroded_image)

    # Display the eroded image
    cv2_imshow(eroded_image)

    print("Eroded image saved as eroded_image.png")