# -*- coding: utf-8 -*-
"""lab 14cv

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gIAmg5nlB0KMrandjmqipkKPlSu1F2YH
"""

import cv2
import numpy as np
from google.colab.patches import cv2_imshow

# Read the image
img = cv2.imread("/content/Picture1.png")

# Check if image is loaded
if img is None:
    print("Error: Could not load image.")
else:
    # Get image dimensions
    rows, cols = img.shape[:2]

    # Define source points
    src_points = np.float32([
        [0, 0],
        [cols - 1, 0],
        [0, rows - 1],
        [cols - 1, rows - 1]
    ])

    # Define destination points
    dst_points = np.float32([
        [0, 0],
        [cols - 1, 0],
        [0, int(0.7 * rows)],
        [cols - 1, int(0.7 * rows)]
    ])

    # Find Homography Matrix
    M, status = cv2.findHomography(src_points, dst_points)

    # Apply Homography Transformation
    homography_img = cv2.warpPerspective(img, M, (cols, rows))

    # Display Original Image
    print("Original Image:")
    cv2_imshow(img)

    # Display Transformed Image
    print("Homography Transformed Image:")
    cv2_imshow(homography_img)

    # Save the transformed image
    cv2.imwrite("/content/transformation_using_Homography_Image.jpg", homography_img)

    print("Homography transformed image saved successfully!")