# -*- coding: utf-8 -*-
"""lab 17cv

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gIAmg5nlB0KMrandjmqipkKPlSu1F2YH
"""

import cv2
from google.colab.patches import cv2_imshow

# Read the image in grayscale
img = cv2.imread("/content/Picture1.png", 0)

# Check if image is loaded
if img is None:
    print("Error: Could not load image.")
else:
    # Apply Sobel X filter
    sobel_x = cv2.Sobel(img, cv2.CV_8U, 1, 0, ksize=5)

    # Display original image
    print("Original Image:")
    cv2_imshow(img)

    # Display Sobel X image
    print("Sobel X Image:")
    cv2_imshow(sobel_x)

    # Save the output image
    cv2.imwrite("/content/sobel_x.jpg", sobel_x)

    print("Sobel X image saved successfully!")