# -*- coding: utf-8 -*-
"""lab 4 cv

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14croMvDyXvDwl-Hl0240Y2vRRJWRDEPq
"""

import cv2
import numpy as np
from google.colab.patches import cv2_imshow

# Read the image in grayscale
img = cv2.imread('/content/Picture1.png', cv2.IMREAD_GRAYSCALE)

# Check if image loaded successfully
if img is None:
    print("Error: Could not load image.")
else:
    # Create a 5x5 kernel
    kernel = np.ones((5, 5), np.uint8)

    # Perform dilation
    dilated_img = cv2.dilate(img, kernel, iterations=1)

    # Save the dilated image
    cv2.imwrite('/content/Dilated_Image.png', dilated_img)

    # Display the dilated image
    cv2_imshow(dilated_img)

    print("Dilated image saved as Dilated_Image.png")