# -*- coding: utf-8 -*-
"""lab 18cv

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gIAmg5nlB0KMrandjmqipkKPlSu1F2YH
"""

import cv2
from google.colab.patches import cv2_imshow

# Read the image in grayscale
img = cv2.imread("/content/Picture1.png", 0)

# Check if image is loaded
if img is None:
    print("Error: Could not load image.")
else:
    # Apply Sobel Y filter
    sobel_y = cv2.Sobel(img, cv2.CV_8U, 0, 1, ksize=5)

    # Display original image
    print("Original Image:")
    cv2_imshow(img)

    # Display Sobel Y image
    print("Sobel Y Image:")
    cv2_imshow(sobel_y)

    # Save the output image
    cv2.imwrite("/content/sobel_y.jpg", sobel_y)

    print("Sobel Y image saved successfully!")