# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14croMvDyXvDwl-Hl0240Y2vRRJWRDEPq
"""

import cv2
from google.colab.patches import cv2_imshow

# Read the image
img = cv2.imread('/content/Picture1.png')

# Check if image loaded successfully
if img is None:
    print("Error: Could not load image.")
else:
    # Convert to grayscale
    gray_img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

    # Display grayscale image
    cv2_imshow(gray_img)

    # Save grayscale image
    cv2.imwrite('/content/gray_image.png', gray_img)

    print("Grayscale image saved successfully!")