# -*- coding: utf-8 -*-
"""lab 13cv

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gIAmg5nlB0KMrandjmqipkKPlSu1F2YH
"""

import cv2
import numpy as np
from google.colab.patches import cv2_imshow

# Read image
img = cv2.imread("/content/Picture1.png")

if img is None:
    print("Error: Could not load image.")
else:
    roi_points = np.float32([
        [150, 200],
        [450, 200],
        [550, 500],
        [50, 500]
    ])

    target_points = np.float32([
        [0, 0],
        [400, 0],
        [400, 600],
        [0, 600]
    ])

    M = cv2.getPerspectiveTransform(roi_points, target_points)

    dst = cv2.warpPerspective(img, M, (400, 600))

    cv2_imshow(img)
    cv2_imshow(dst)

    cv2.imwrite("/content/Perspective_Output.jpg", dst)

    print("Perspective transformation completed successfully!")