# -*- coding: utf-8 -*-
"""lab 7cv

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14croMvDyXvDwl-Hl0240Y2vRRJWRDEPq
"""

import cv2
from google.colab.patches import cv2_imshow

# Open the video
cap = cv2.VideoCapture('/content/demonslayer.mp4')

# Check if video opened successfully
if not cap.isOpened():
    print("Error: Could not open video.")
else:
    while True:
        ret, frame = cap.read()

        if not ret:
            break

        # Slow Motion
        slow_frame = cv2.resize(frame, None, fx=0.5, fy=0.5)
        cv2_imshow(slow_frame)
        cv2.waitKey(100)

        # Fast Motion
        fast_frame = cv2.resize(frame, None, fx=2.0, fy=2.0)
        cv2_imshow(fast_frame)
        cv2.waitKey(10)

cap.release()
cv2.destroyAllWindows()