# -*- coding: utf-8 -*-
"""lab 9cv

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14croMvDyXvDwl-Hl0240Y2vRRJWRDEPq
"""

import cv2
import os

# Display current working directory
print("Current Working Directory:", os.getcwd())

# Image file name (make sure Picture1.png is in the current folder)
image_path = "Picture1.png"

# Read the image
img = cv2.imread(image_path)

# Check if image is loaded successfully
if img is None:
    print("Error: Image not found!")
    print("Make sure 'Picture1.png' is in the current working directory.")
else:
    # Rotate image 90 degrees clockwise
    rotated_img = cv2.rotate(img, cv2.ROTATE_90_CLOCKWISE)

    # Save rotated image
    cv2.imwrite("rotated_image.png", rotated_img)

    print("Image rotated successfully!")
    print("Saved as: rotated_image.png")