# -*- coding: utf-8 -*-
"""lab 8cv

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14croMvDyXvDwl-Hl0240Y2vRRJWRDEPq
"""

import cv2
from google.colab.patches import cv2_imshow

# Read the image
image = cv2.imread('/content/Picture1.png')

# Check if image loaded
if image is None:
    print("Error: Could not load image.")
else:
    # Get image dimensions
    height, width = image.shape[:2]

    # Enlarge image
    scale_factor = 3.0
    bigger_image = cv2.resize(image, (int(width * scale_factor), int(height * scale_factor)))

    # Shrink image
    scale_factor = 0.5
    smaller_image = cv2.resize(image, (int(width * scale_factor), int(height * scale_factor)))

    # Display images
    print("Original Image")
    cv2_imshow(image)

    print("Bigger Image")
    cv2_imshow(bigger_image)

    print("Smaller Image")
    cv2_imshow(smaller_image)

    # Save images
    cv2.imwrite('/content/Bigger_image.png', bigger_image)
    cv2.imwrite('/content/Smaller_image.png', smaller_image)

    print("Images saved successfully!")