# -*- coding: utf-8 -*-
"""lab 2 cv

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14croMvDyXvDwl-Hl0240Y2vRRJWRDEPq
"""

import cv2
from google.colab.patches import cv2_imshow

# Read the image
image = cv2.imread('/content/Picture1.png')

# Check if image loaded successfully
if image is None:
    print("Error: Could not load image.")
else:
    # Apply Gaussian Blur
    blur = cv2.GaussianBlur(image, (5, 5), 10)

    # Save blurred image
    cv2.imwrite('/content/blurred_image.png', blur)

    # Display blurred image
    cv2_imshow(blur)

    print("Blurred image saved as blurred_image.png")