# -*- coding: utf-8 -*-
"""lab 12cv

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gIAmg5nlB0KMrandjmqipkKPlSu1F2YH
"""

import cv2
import numpy as np
from google.colab.patches import cv2_imshow

# Read the image
img = cv2.imread("/content/Picture1.png")

# Check if image is loaded
if img is None:
    print("Error: Could not load image.")
else:
    # Get image dimensions
    rows, cols = img.shape[:2]

    # Source points
    src_points = np.float32([
        [0, 0],
        [cols - 1, 0],
        [0, rows - 1],
        [cols - 1, rows - 1]
    ])

    # Destination points
    dst_points = np.float32([
        [0, 0],
        [cols - 1, 0],
        [int(0.33 * cols), rows - 1],
        [int(0.66 * cols), rows - 1]
    ])

    # Perspective transformation matrix
    M = cv2.getPerspectiveTransform(src_points, dst_points)

    # Apply perspective transformation
    perspective_img = cv2.warpPerspective(img, M, (cols, rows))

    # Display transformed image
    cv2_imshow(perspective_img)

    # Save transformed image
    cv2.imwrite("/content/Perspective_Transformed_Image.jpg", perspective_img)

    print("Perspective transformed image saved successfully!")