# -*- coding: utf-8 -*-
"""lab 14cv

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gIAmg5nlB0KMrandjmqipkKPlSu1F2YH
"""

import cv2
from google.colab.patches import cv2_imshow

# Read the image in grayscale
img = cv2.imread("/content/Picture1.png", 0)

# Check if image is loaded
if img is None:
    print("Error: Could not load image.")
else:
    # Apply Canny Edge Detection
    edges = cv2.Canny(img, 100, 200)

    # Display original image
    print("Original Image:")
    cv2_imshow(img)

    # Display edge-detected image
    print("Edge Detected Image:")
    cv2_imshow(edges)

    # Save the edge image
    cv2.imwrite("/content/Edges.jpg", edges)

    print("Edge detected image saved successfully!")