# -*- coding: utf-8 -*-
"""lab 18cv

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gIAmg5nlB0KMrandjmqipkKPlSu1F2YH
"""

import cv2
from google.colab.patches import cv2_imshow

# Read the image in grayscale
img = cv2.imread("/content/Picture1.png", 0)

# Check if image is loaded
if img is None:
    print("Error: Could not load image.")
else:
    # Apply Sobel X and Sobel Y
    sobelx = cv2.Sobel(img, cv2.CV_64F, 1, 0, ksize=3)
    sobely = cv2.Sobel(img, cv2.CV_64F, 0, 1, ksize=3)

    # Combine both edges
    edges = cv2.addWeighted(sobelx, 0.5, sobely, 0.5, 0)

    # Convert to unsigned 8-bit image
    edges = cv2.convertScaleAbs(edges)

    # Display Original Image
    print("Original Image:")
    cv2_imshow(img)

    # Display Edge Detection Image
    print("Edge Detection Image:")
    cv2_imshow(edges)

    # Save the output image
    cv2.imwrite("/content/Edge_detection.jpg", edges)

    print("Edge detection image saved successfully!")