# -*- coding: utf-8 -*-
"""lab 11cv

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gIAmg5nlB0KMrandjmqipkKPlSu1F2YH
"""

import cv2
import numpy as np
from google.colab.patches import cv2_imshow

# Read the image
img = cv2.imread("/content/Picture1.png")

# Check if image is loaded
if img is None:
    print("Error: Could not load image.")
else:
    # Get image size
    rows, cols = img.shape[:2]

    # Translation matrix (move image 100 pixels right and 50 pixels down)
    M = np.float32([[1, 0, 100], [0, 1, 50]])

    # Apply affine transformation
    affine_img = cv2.warpAffine(img, M, (cols, rows))

    # Display transformed image
    cv2_imshow(affine_img)

    # Save transformed image
    cv2.imwrite("/content/Affine_Transformed.jpg", affine_img)

    print("Affine transformed image saved successfully!")